### ISSUE TITLE
Pressing left arrow after jump move cursor to beginning [VS17] 

### ISSUE THREAD

**Issue by merdigon** [jsturtevant/ace-jump#10]
When I press left arrow, after jump, cursor is moved to place, where I started my jump.
Found on Visual Studio 2017.

EDIT: works on every arrow keys.

**Comment by merdigon** [comment]
I need to be more specific:
It's only happens when I select text , then do the jump and press any arrow. It goes back at the beginning of selected text.
Most popular scenario is when you click "Go to definition" and "Go to implementation". VS select method name and jump without deselecting text makes this issue occurs.

**Comment by merdigon** [comment]
Also down arrow has similar problem

**Comment by maleet** [comment]
It's connected with Visual Studio. Visual Studio is capturing lot of shortcuts. I have custom screenshot application and if the focus in in VS then no action from pressing print screen button. 

I don't know if it can be somehow forced to work, but these kind of problems are present with other applications also inside VS.
