### ISSUE TITLE
Is it possible to work with vsvim to define activation keys in different mode?

### ISSUE THREAD

**Issue by xarthurx** [jsturtevant/ace-jump#17]
Say only in normal mode with a single key？

**Comment by mgutekunst** [comment]
Thats possible. For example, I bound it to `<Space>` in normal mode. Here's the line i put into my ~/.vsvimrc

`nnoremap <Space> :vsc Tools.InvokeAceJumpCommand<CR>
`

**Comment by xarthurx** [comment]
This is great!
Thank you very much.
