### ISSUE TITLE
Change key that activates extension

### ISSUE THREAD

**Issue by mgutekunst** [jsturtevant/ace-jump#2]
Hi, 
thanks for writing this extension.

I'm just wondering if there's a way to change the keybinding to activate it. You wrote it's bound to Ctrl + Alt + ; but that's not working for me so I wanted to change the keybinding. Unfortunately I couldn't find the corressonding command in the keyboard settings. 

Also it seems the extension is only working with US keyboard layout set. 

Kind regards, 
Manuel Gutekunst

**Comment by jsturtevant** [comment]
Your welcome!  Currently the only way to change the binding is to edit the source and recompile.  I didn't know how to attach the keybinding to the VS shortcuts and decided to wait till I got enough feedback to make the change.  Do you have any experience with extensions and  a willingness to help out?

For the keyboard layout, I am not even sure where to begin...  I'd be happy to think about it but have no experience or way to test. Maybe you have some ability to help guide me?

**Comment by mgutekunst** [comment]
Sorry, I havent't written an extension for Visual Studio yet. But I'm curious how this works so I'll give it a try.

**Comment by jsturtevant** [comment]
No worries!  Give it a try, this was my first.  Let me know if there are any stumbling blocks and we can try to work through it.

**Comment by jsturtevant** [comment]
Any luck?

**Comment by mgutekunst** [comment]
Sorry, I haven't even cloned your project yet. I've got another project that I want to finish first.

**Comment by jsturtevant** [comment]
No worries.  Just checking in.

**Comment by maleet** [comment]
+1

**Comment by mgutekunst** [comment]
Hi, 
I was able to create a command. For testing purposes I bound it to Ctrl+J using Options->Keyboard. 

But I have a problem when switching buffers which I couldn't solve yet.

**Comment by jsturtevant** [comment]
Cool! Do you have code available? Maybe open a PR?

**Comment by mgutekunst** [comment]
Sure, Code is available here: https://github.com/mgutekunst/ace-jump/tree/CustomCommand 
But you probably want to have a look at revision https://github.com/mgutekunst/ace-jump/commit/836463d0faadd4718031d076eff7383df77734b6. I had to return my Windows Notebook so I committed things that did not work :)

Since jumping does not work any time and I still need to fix buffer switches, opening  a PR would result in a broken plugin.

**Comment by maleet** [comment]
As I use Estonian keyboard then this extension isn't usable until this feature :) I'm in waiting list :) Have been using ace for webstorm and visual studio would be so much better with this.

**Comment by mgutekunst** [comment]
Hi, 

I think i fixed the remaining Issues (I hope so at least ;) ). I created a pull request: https://github.com/jsturtevant/ace-jump/pull/5

I couldn't test if this works with Visual studio versions other than 2015.
