### ISSUE TITLE
Doesn't work with vsvim unfortunately!

### ISSUE THREAD

**Issue by spiralsam** [jsturtevant/ace-jump#3]
Hey this is seriously like in the top 10 extensions ever create for VS. It doesn't work with VsVim though unfortunately despite somebody claiming that does in the review/comments! Any chance to make it work?

**Comment by jsturtevant** [comment]
Thanks for the complement! Do you have any further information on what happens when it doesn't work?  Is there an error message?  Does the jumpbox show up?   

Any further information would be helpful.  I have had interest from the community for new features and can look at this as a possible update.

**Comment by GnoX** [comment]
Everything works just fine, except that when you enter character that you want to jump to, it executes that command. It also executes it when you are jumping and these things make it unusable when using it with VsVim.

For example if you want to jump to character s, it will substitute current character (removes it and enters insert mode) and then you press S, it will write it to location that you jumped to.

**Comment by jsturtevant** [comment]
That kind of sounds like there is a key binding conflict.  Issue #2 is being working in PR #5 which will allow you to change the key combination.  Once that issue is merged let's see if changing the key combination solves the issue.

**Comment by GnoX** [comment]
I believe that that will not solve that issue. From my logical standpoint, once you open jumpbox, you are handling next few key presses and this will presumably disable character insertion. Problem is that VsVim is handling those key presses its own way as well.
I don't know if there is any way to interact with other plugins, but if you disable VsVim for jump key presses, it would work.
This is my theory of what's happening, but I could be easily mistaken. I hope this does help you a bit.

**Comment by mgutekunst** [comment]
Hi, 
I tested #5  with VsVim. It's working somehow. If you're in normal mode and trigger AceJump all keystrokes are handled by VsVim. But if you switch to insert mode (which is possible even after triggering AceJump) the key will be forwarded to AceJump. What I didn't find out was a way to programmatically switch to insert mode after triggrering AceJump.

**Comment by jsturtevant** [comment]
PR #6 makes this work better with VsVim.  

There is still a known issue if you try to use ace-jump in visual mode. After
jumping, it first seems that the selection is discarded. But after
moving the cursors once more, the visual selection is enabled again.

Closing this and opening a specific issue for this case.
